### ISSUE TITLE
[Bug] Could not install the certificate 

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/proxyman-windows-linux#124]
## Description
A user reports that they could not install the certificate on their Windows machine. We asked them to share the Windows version for the investigation.

- Error_Invalid_Parameter
![unnamed](https://user-images.githubusercontent.com/5878421/196904544-80d98375-4643-4406-a1e6-16057671b25b.png)

=> It seems the `CertUtils.exe` doesn't support the flag `-addstore`

## Expected Behavior
- Find a solution to make it works

## Current Behavior
- There is an error when installing the certificate.

**Comment by kics223w1** [comment]
I'm not sure that is Windows 10 or 11?

**Comment by NghiaTranUIT** [comment]
Look like it's Windows 10. I email them to ask what the Windows version is. Maybe they will get back soon.

**Comment by kics223w1** [comment]
Continue on [#125](https://github.com/ProxymanApp/proxyman-windows-linux/issues/125)
