### ISSUE TITLE
[BUG] When Exporting a Request/Response Body, the file name doesn't contain the file extension

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/proxyman-windows-linux#294]
## Description
As title.

## Steps to Reproduce
1. Open Proxyman for Windows -> Open this URL: https://user-images.githubusercontent.com/5878421/258680109-dd5d2543-024b-4a7a-9eeb-4b8b0046c5a3.jpg
2. Enable SSL Proxying on this domain -> Re-send the URL again
3. Right-click on new request -> Export -> Response Body
4. Save to the desktop with the default name

## Current Behavior
- The file doesn't contain the File Extension -> Can't double click to open it

## Expected Behavior
- Should detect the file format, and add the file extension properly.

## How to detect the file extension
1. Try to parse the URL (Use `NodeJS Path`: https://nodejs.org/api/path.html#pathextnamepath) -> If it contains the files extension -> Use it
2. If there is no file extension, use this lib [file-type](https://www.npmjs.com/package/file-type) to detect the bytes -> Get extension
3. Otherwise, if there are no extensions, just don't add the extension to the file filename.

## Test cases
- Test with PNG, JPG
- PDF, MP4
- Text-base (txt)

## Environment

- App version:
- Windows/Linux version:

**Comment by kics223w1** [comment]
Unable to reproduce the bug, but I will add unit tests and update the code of the export function

**Comment by NghiaTranUIT** [comment]
It seems I can't reproduce the bug anymore. I will close this ticket for further investigation.
