### ISSUE TITLE
the program already is great. i just want to add Some suggestions

### ISSUE THREAD

**Issue by unknowen700** [ProxymanApp/proxyman-windows-linux#318]
## Description
the program already is great. i just want to add Some suggestions
 
1- can you pls add dark mode 
2 -  can you stop the app to navigate to saved or pinned tap when user click save or pin request 
some times you cheek for request and save them for later and when the app navigate your lose current focus on all request you examine 
3- add method to save tap when user edit and reply request should be able to save the edited request 
4- it there any news about scripting tool in win version that tool is really helpful

**Comment by kics223w1** [comment]
- Hi @unknowen700, thank you for the suggestions.
 - For the dark mode, we already have the ticket [Support Dark Theme](https://github.com/ProxymanApp/proxyman-windows-linux/issues/286), it's already in our To-Do list.
 - For the numbers two and three, I will suggest those to the founder and implement them if he accepts.
 - About the scripting tool, it will be implemented after the [Network Condition Tool](https://docs.proxyman.io/advanced-features/network-throttling) is released.
