### ISSUE TITLE
can i add some suggestion for this great project 

### ISSUE THREAD

**Issue by unknowen700** [ProxymanApp/proxyman-windows-linux#333]
1- can you pls allow to save request in  collection like in pinned - this will help when I'm hunting on website 
2-  sometimes when i edit value in URL is take time to change in body so i have to change from raw to make sure everything is correct
3- copy text not working in in request or response  ar header or cookies its only working in raw or body
4- add cancel request when i send request and its take long to respond or something happen i had to restart proxy server to end connection 
5- 

thank you for this great program is really helping me so much.

**Comment by kics223w1** [comment]
3. You can select the text then click `Ctrl + C` or right click and click on the menu item to copy the tet
4. You can simply delete the request to close the connection, if you restart the proxy server all connection will be closed.

 - I've recored the video ( 26 seconds ) to show how I did that. [2023-11-19 22-04-58.zip](https://github.com/ProxymanApp/proxyman-windows-linux/files/13403594/2023-11-19.22-04-58.zip)

**Comment by unknowen700** [comment]
1- i mean url at Compose  when i use tool edit and repat  so when i edit something in URL take some time to change in real request  but if edit from raw changed and no problem happened 

2- about copy that's the problem i saw in your screen its work with now problem but in my device isn't so now i will cheek again if problem from my device or something - when i try select the text then click Ctrl + C or right click and click on the menu item Copy noting happen and value not copied but when i try  from raw  when i copy from raw its copy with no problem  that happen with any value 
i think its problem about visual 

4. thank you for let me know that about delete request your really so helpful man

**Comment by unknowen700** [comment]
i think i found the problem about copy text its work if i select more then one line 


https://github.com/ProxymanApp/proxyman-windows-linux/assets/86002517/d4e278c5-9166-4be8-b858-20aab907a4a2

**Comment by unknowen700** [comment]
Compose  URL problem : that what happen sometimes i Cheak for endpoints or send request to different path i click send and i think the response is for new url but i found that its not changed yet and response is for the old url or path 

Uploading bandicam 2023-11-20 01-02-42-651.mp4…

**Comment by kics223w1** [comment]
> i think i found the problem about copy text its work if i select more then one line but not work if i wany copy only 1 line value
 - It seems like it's a bug when we copy 1 value in Header Tab, I will fix this in 2.8.0.
 - For the Compose URL, we will refactor the code to fix your problem

**Comment by unknowen700** [comment]
thank you and you relay have great project

**Comment by unknowen700** [comment]
everything has been fixed in only 1 day your really so great your project should be number 1 i did try burb and other toold intercept  and i couldn't work like in your program.
