### ISSUE TITLE
Linux version 2.9.0 - Port can't be changed [Pro version enabled]

### ISSUE THREAD

**Issue by ReneNulschDE** [ProxymanApp/proxyman-windows-linux#357]
## Description
I try to change the port from 9090 to 20000. Change gets not saved. Port is free. Same test with burp is successful

## Steps to Reproduce

1. Open proxyman on linux (appimage 2.9.0)

2. Go to Preferences, change proxy port to 20000, go to next tab, go back --> changed back to 9090
or 
2. Go to Preferences, change proxy port to 20000, close dialog --> not changed

4.

## Current Behavior

See desciption and Repro Steps
[Screencast from 2024-01-25 19-28-58.webm](https://github.com/ProxymanApp/proxyman-windows-linux/assets/33263735/2a5bad0f-c0e4-47eb-b09a-7a99e853c3e6)

## Expected Behavior

Port is saved and is listening on this port after closing the dialog
## Environment

- App version:
- Windows/Linux version:
Linux 2.9.0
Distro: Ubuntu 23.10

**Comment by NghiaTranUIT** [comment]
@kics223w1 please check it out 👍

**Comment by kics223w1** [comment]
Hi @ReneNulschDE 
It requires pressing `Enter` to notify Proxyman to change the port. I think you didn't press `Enter` after finishing typing.
I'm going to change this behavior to update the port as soon as the user finishes typing.

**Comment by NghiaTranUIT** [comment]
Yes, there are few ways to update the port number:
- Hit Enter 
- Or just Tab to leave the focus ring 
- hit ESC to close the Setting.
- Or switch to different tab

In general, if the Port Text fields is end of editing -> Save it and switch to new port if the new port is changed.

**Comment by NghiaTranUIT** [comment]
@ReneNulschDE it's fixed. You can try on the latest build v4.10.0 at https://download.proxyman.io/linux/2.10.0/build/Proxyman-2.10.0.AppImage

**Comment by ReneNulschDE** [comment]
Perfect. Thx. - Donwloaded and I can confirm the functionality.
