### ISSUE TITLE
Multipart form data broken if used with scripting 

### ISSUE THREAD

**Issue by mariusvn** [ProxymanApp/proxyman-windows-linux#383]
## Description

When I have a multipart form data and I use a script to edit the request (without editing the body), the body is modified to "{string of the body}". This breaks the multipart form

## Steps to Reproduce

1. Add a script (the default one has the bug so no need to edit it)

2. Enable the request modification (the request checkbox on the top of the script editor)

3. Do a multipart form request

## Current Behavior

The request body is encoded as a json (if im not wrong

## Expected Behavior

keep the text as-is

## Environment

- App version: 2.11.1
- Windows/Linux version: Windows 11 Pro

---
*just a note about adding scripting: this is so nice, thanks for the work, it just works well in most cases and allow so much possibilities, thanks*

**Comment by mariusvn** [comment]
<img width="694" alt="Proxyman_p0uhgADn0p" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/4770874/7f1b07fc-e917-48b6-ac6e-6f2de7d59d78">

**Comment by mariusvn** [comment]
<img width="792" alt="Proxyman_PerXNKgqOh" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/4770874/bc4c045e-6dca-409d-91d8-0f1525f2dd77">

**Comment by NghiaTranUIT** [comment]
Thanks @mariusvn. It's a bug. Let us fix it @kics223w1 and send you a Beta build 👍

**Comment by NghiaTranUIT** [comment]
It's fixed @mariusvn we will release it in the new update. ETA this week 👍

**Comment by mariusvn** [comment]
nice to hear 👍

**Comment by NghiaTranUIT** [comment]
@mariusvn new build is released v2.12.0  🎉 

If you don't mind, Please give it a try and share with me the result 👍

**Comment by mariusvn** [comment]
I do not have the bug anymore, thanks for the reactivity !

**Comment by kics223w1** [comment]
Happy to hear that 👍🏻
