### ISSUE TITLE
not able to open saved session from macOS in Windows

### ISSUE THREAD

**Issue by FachrulCH** [ProxymanApp/proxyman-windows-linux#406]
## Description
Given I had file.proxymansessionv2 that exported from proxyman mac version
When I open this file in Windows proxyman
Then app throws error 

<img width="662" alt="image" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/10245158/aa0ef0ec-e5d4-4224-8df8-f57b3b32ba09">

## Steps to Reproduce

1. Save session from proxyman MacOS

2. Shared to windows user

3. open in proxyman Windows

## Current Behavior
App throw error and unable to load the file

## Expected Behavior
the file proxymansessionv2 should be compatible and platform agnostic

## Environment

- App version: Version 2.14.0
- Windows/Linux version: 
```Edition	Windows 11 Pro
Version	23H2
OS build	22631.3527
Experience	Windows Feature Experience Pack 1000.22700.1003.0
```

**Comment by kics223w1** [comment]
Hi @FachrulCH 
This feature has not been implemented yet. You can track the progress in our roadmap to see when this feature will be completed 👍🏻 

This is our roadmap https://github.com/ProxymanApp/proxyman-windows-linux/projects/1 
And this is the proxymansessionv2 ticket https://github.com/ProxymanApp/proxyman-windows-linux/projects/1

**Comment by NghiaTranUIT** [comment]
@FachrulCH you can right click on the folder, app, domains -> Export -> ProxymanLog 

Then, importing it to Proxyman Windows.

ProxymanSession hasn't implemented yet on Windows.

**Comment by FachrulCH** [comment]
ah sure,, well noted 👍
