### ISSUE TITLE
A request with the error Content-Type blocked and could not display the body

### ISSUE THREAD

**Issue by ouzezh** [ProxymanApp/proxyman-windows-linux#421]
## Description
A request with the error Content-Type blocked and could not display the body.

## Steps to Reproduce
1.enable script with host www.baidu.com
2.create a post request https://www.baidu.com
3.set Content-Type : application/json;charset=UTF-8
4.set Illegal json format body: abc
5.click send request

## Current Behavior
The request is blocked, and the request body is "Empty Body"
![image](https://github.com/user-attachments/assets/4e966368-ef43-43a1-bcc3-96322967302f)

## Expected Behavior
The request executes normally and the body is displayed normally

## Environment

- App version: 2.15.0
- Windows/Linux version: Windows 10 Enterprise Edition

**Comment by NghiaTranUIT** [comment]
It's expected behavior. Since you're using the Scripting, your JSON is invalid, so it can't parse the JSON -> Won't show the body.

**Comment by ouzezh** [comment]
Thanks for answering
