### ISSUE TITLE
Is there a way to see response data for streaming API calls (eg. endpoints meant for receiving Server sent events) 

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/proxyman-windows-linux#453]
## Description
- Ticket: https://github.com/ProxymanApp/Proxyman/issues/1323#issuecomment-1985003144

## Acceptance Criteria
- [x] Support SEE event in Proxyman
- [x] Ping @NghiaTranUIT to get the NodeJS script to simulate the SSE event for testing 
- [x] Write Unit Tests

**Comment by kics223w1** [comment]
I think this feature has already been implemented in [[BUG] Server-Sent Event (SSE) doesn't work](https://github.com/ProxymanApp/proxyman-windows-linux/issues/387)
